name    'treydock-ossec'
version '0.0.1'
source 'git://github.com/treydock/puppet-ossec.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Puppet module to manage OSSEC'
description 'Puppet module to manage OSSEC'
project_page 'https://github.com/treydock/puppet-ossec'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
